parameters:
#    sensio_training.example.class: Sensio\Bundle\TrainingBundle\Example

services:
#    sensio_training.example:
#        class: %sensio_training.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
