<?php

namespace Sensio\Bundle\TrainingBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ColorController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sensio\Bundle\TrainingBundle\Controller\ColorController();
        return $instance;
    }
}
